version: '3'

services:
  #HDFS
  namenode:
    container_name: namenode
    image: hadoop:base
    hostname: namenode
    restart: unless-stopped
    command: "/opt/init_container.d/namenode/init.sh"
    depends_on:
      - datanode
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 9870:9870 #dfs.namenode.http-address

  datanode:
    container_name: datanode-0
    image: hadoop:base
    hostname: datanode-0
    restart: unless-stopped
    command: "/opt/init_container.d/datanode/init.sh"
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 9864:9864 #dfs.datanode.http.address


  #YARN
  resourcemanager:
    container_name: resourcemanager
    image: hadoop:base
    hostname: resourcemanager
    restart: unless-stopped
    command: "/opt/init_container.d/resourcemanager/init.sh"
    depends_on:
      - "namenode"
      - "nodemanager-0"
      - "nodemanager-1"
      - "nodemanager-2"
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 8088:8088 #yarn.resourcemanager.webapp.address
      - 8031:8031 #yarn.resourcemanager.resource-tracker.address
      - 8030:8030 #yarn.resourcemanager.scheduler.address
      - 8033:8033 #yarn.resourcemanager.admin.address
      - 10200:10200 #yarn.timeline-service.address
      - 8188:8188 #yarn.timeline-service.webapp.address
      - 19888:19888 #mapreduce.jobhistory.webapp.address

  nodemanager-0:
    container_name: "nodemanager-0"
    image: hadoop:base
    hostname: "nodemanager-0"
    restart: unless-stopped
    command: "/opt/init_container.d/nodemanager/init.sh"
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 8042:8042 #yarn.nodemanager.webapp.address

  nodemanager-1:
    container_name: "nodemanager-1"
    image: hadoop:base
    hostname: "nodemanager-1"
    restart: unless-stopped
    command: "/opt/init_container.d/nodemanager/init.sh"
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 8043:8042 #yarn.nodemanager.webapp.address


  nodemanager-2:
    container_name: "nodemanager-2"
    image: hadoop:base
    hostname: "nodemanager-2"
    restart: unless-stopped
    command: "/opt/init_container.d/nodemanager/init.sh"
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 8044:8042 #yarn.nodemanager.webapp.address
networks:
  yarn-net:
