version: '3'

services:
  #HDFS
  namenode:
    container_name: namenode
    image: hadoop:base
    restart: unless-stopped
    command: "/opt/init_container.d/namenode/init.sh"
    depends_on:
      - datanode
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 9870:9870 #dfs.namenode.http-address

  datanode:
    container_name: datanode-0
    image: hadoop:base
    restart: unless-stopped
    command: "/opt/init_container.d/datanode/init.sh"
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 9864:9864 #dfs.datanode.http.address


  #YARN
  resourcemanager:
    container_name: resourcemanager
    image: hadoop:base
    restart: unless-stopped
    command: "/opt/init_container.d/resourcemanager/init.sh"
    depends_on:
      - nodemanager
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 8088:8088 #yarn.resourcemanager.webapp.address
      - 8031:8031 #yarn.resourcemanager.resource-tracker.address
      - 8030:8030 #yarn.resourcemanager.scheduler.address
      - 8033:8033 #yarn.resourcemanager.admin.address
      - 19888:19888 #mapreduce.jobhistory.webapp.address

  nodemanager:
    container_name: nodemanager-0
    image: hadoop:base
    restart: unless-stopped
    command: "/opt/init_container.d/nodemanager/init.sh"
    build:
      context: base
    networks:
      - yarn-net
    ports:
      - 8042:8042 #yarn.nodemanager.webapp.address

networks:
  yarn-net:
